### ISSUE TITLE
nvml.dll and nvml.so is missing on latest version

### ISSUE THREAD

**Issue by Pointing8422** [SveSop/nvidia-libs#14] opened 2023-12-10 01:45 UTC
nvml windows and linux files is missing and it gives and error on the installer file. On the previous version the files are present, so copy pasting the latest version on the previos version folder fix everything.

**Comment by SveSop** [comment] 2023-12-11 15:50
Which of the installer files? I know i had a bug in the proton script that i just updated, but other than that it seems to work for me.

OBS! Be aware that 32-bit nvml is no longer supported ref to https://github.com/Saancreed/wine-nvml/commit/e37cb265152f80312970e94be731dc82563688a9

**Comment by Pointing8422** [comment] 2023-12-16 14:08
Yep, it was that nvml on 32 bit files dissappeared, but on the install script it still tries to install it. I was thinking something was missing.

**Comment by SveSop** [comment] 2023-12-16 15:17
Hopefully the issue is fixed with https://github.com/SveSop/nvidia-libs/commit/707ac7cab23aa962fde2d51ff6b7fe610fad134b So closing this

**Closed** 2023-12-16 15:16 UTC
